[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
internalPort = 8001
protocol = "TCP"

  [[services.ports]]
  source = 8001
  target = 8001
